### ISSUE TITLE
Humble  /camera_info_manager.hpp: No such file or directory

### ISSUE THREAD

**Issue by samuk** [surfertas/ros2_ipcamera#15]
I'm trying to compile on Humble and get the above error. 

Please also see below link
https://github.com/ros-perception/image_common/issues/250

Any idea what I can try next?

**Comment by surfertas** [comment]
Hey sorry just saw this. Were you able to resolve the issue?

**Comment by samuk** [comment]
No still the same. Not really made progress. Do you have any ideas?

I guess the .hpp was removed after Foxy? https://github.com/ros-perception/image_common/tree/noetic-devel/camera_info_manager/src

It looks like you depend on it here: https://github.com/surfertas/ros2_ipcamera/blob/master/include/ros2_ipcamera/ipcamera_component.hpp#L24
